language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install scikit-learn
  - pip install pytest
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests
